### ISSUE TITLE
How can I run it online?

### ISSUE THREAD

**Issue by jututt** [B1NT0N/XMR_poll_bot#2]
Like in pythonanywhere?
I get error Max retries exceeded, OSError Tunnel connection failed: 403 forbidden

**Comment by B1NT0N** [comment]
That's a connection error
Make sure you have configured your .env file with your telegram bot token

**Comment by jututt** [comment]
I commented out the env lines on my script, it works when running on local machine, can you explain why? thanks

**Comment by jututt** [comment]
Btw, I set up the script using the .env file and uploading it too, but I still get the Proxy Error of above

**Comment by B1NT0N** [comment]
I think the correct way to use environmental variables on Heroku is to set them in your App -> Setting -> Config Vars
