### ISSUE TITLE
List all the workers in a single message

### ISSUE THREAD

**Issue by jututt** [B1NT0N/XMR_poll_bot#4]
Hi @B1NT0N
I tweaked your code on my private repo to have all the workers info in one line.

```
  if new_msg == "/rigs" or new_msg == "/r" or new_msg == "r":
                mining_data = get_data(wallet)
                for worker in mining_data["perWorkerStats"]:
                    send_message_only(data,
                                f'*{worker["workerId"][:3]}* '
                                f'*{worker["hashrate"][:4] if ("hashrate" in worker) is True else "*---*"}*  '
                                f'{str(round((float(worker["hashes"])/10**9), 3))} bil  '
                                f'{datetime.fromtimestamp(int(worker["lastShare"])).strftime("%d %b %H:%M")}'
                                )
```
I currently have 6 workers, so the above code prints 6 messages.

Would it be possible to have all the workers listed in a single 6-lines message?
Thanks

**Comment by B1NT0N** [comment]
Yes, It is possible.
Maybe on next update I will make it so all the info will be in a single long message.
Made it that way because I only have 1 worker and couldn't test for multiple workers.
