### ISSUE TITLE
Schedule automatic message

### ISSUE THREAD

**Issue by jututt** [B1NT0N/XMR_poll_bot#6]
Hi @B1NT0N 
how would you add feature to send automatically scheduled messages every x hours?
i.e. I would like my bot to print my workers stats every 4 hours.
Thanks

**Comment by B1NT0N** [comment]
Hi.
Just use a condition inside the `while` loop to check if the current hour is divisible by the time interval. Example:
```
if (current_hour % time_interval) == 0:
      (...) #send message function
```
Be careful with while loop since it can crash your script.
I will let you the goal of optimizing it in order to send the message only once and avoid crashing the script.
